import type { Metadata } from "next";
import { DM_Sans, Aoboshi_One } from "next/font/google";
import "../styles/globals.css";

const dmSans = DM_Sans({ subsets: ["latin"] });
const aoboshiOne = Aoboshi_One({ 
  weight: '400',
  subsets: ["latin"],
  variable: '--font-aoboshi-one'
});

export const metadata: Metadata = {
  title: "Anima Project - Automatically generated by Anima",
  description: "A Next.js project automatically generated by Anima using the Shadcn UI library",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} ${aoboshiOne.variable}`}>{children}</body>
    </html>
  );
}